### ISSUE TITLE
March week 1 mumbai todo list

### ISSUE THREAD

**Issue by kurtzace** [kurtzace/diary2023#4]
# raw material
- [x] wax tablet mould
- [x] gratitude journal

# babu
- [x] aryaveer nail cutter
- [x] aryaveer books

- [x] **mummy**
- bua souvenir
- bade papa "
- muttery
- dry fruits holi
- dress

## Others
- [x] Shave kit
- [x] prints of wax tablet
- [x] upload fuel and mobile bills2 Ramco
- [ ] send artisane sticker message to mummy
- [x] download course offline
- [ ] download Competitive coding book offline
- [x] Video of kk thank you speech extraction
- [ ] plan for tech events post arrival
 - [x] soap blog

**Comment by kurtzace** [comment]
## part 2
- [x] ahd grocery
- [x] diaper bottom
- [x] shipping label mummy 
- [x] ac cleaner
- [ ] table assembly raise request 
- [ ] survey softner
- [ ] buy domain
- [ ] mail address
- [ ] o2vend register 
- [x] o2vend send specs
- [ ] apply for current account 
- [ ] activate airtel sim
- [x] suneel papa video extract
- [x] airtel transfer mail 
- [ ] fitness journal
